# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\rstoragelambda\"\xb1\x01\n\x11\x43\x61llActionRequest\x12\x13\n\x0b\x61\x63tion_name\x18\x01 \x01(\t\x12O\n\x10\x61\x63tion_arguments\x18\x02 \x03(\x0b\x32\x35.storagelambda.CallActionRequest.ActionArgumentsEntry\x1a\x36\n\x14\x41\x63tionArgumentsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\";\n\x1b\x43\x61llStatelessActionResponse\x12\r\n\x05\x66inal\x18\x01 \x01(\x08\x12\r\n\x05\x63hunk\x18\n \x01(\x0c\"\xc1\x01\n\x19\x43\x61llStatefulActionRequest\x12\x13\n\x0b\x61\x63tion_name\x18\x01 \x01(\t\x12W\n\x10\x61\x63tion_arguments\x18\x02 \x03(\x0b\x32=.storagelambda.CallStatefulActionRequest.ActionArgumentsEntry\x1a\x36\n\x14\x41\x63tionArgumentsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"<\n\x1a\x43\x61llStatefulActionResponse\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\r\n\x05parts\x18\x02 \x01(\x05\"9\n\x18GetStatefulResultRequest\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\x0c\n\x04part\x18\x02 \x01(\x05\"9\n\x19GetStatefulResultResponse\x12\r\n\x05\x66inal\x18\x01 \x01(\x08\x12\r\n\x05\x63hunk\x18\n \x01(\x0c\x32\xd6\x02\n\x14StorageLambdaService\x12g\n\x13\x43\x61llStatelessAction\x12 .storagelambda.CallActionRequest\x1a*.storagelambda.CallStatelessActionResponse\"\x00\x30\x01\x12\x63\n\x12\x43\x61llStatefulAction\x12 .storagelambda.CallActionRequest\x1a).storagelambda.CallStatefulActionResponse\"\x00\x12p\n\x17GetStatefulActionResult\x12\'.storagelambda.GetStatefulResultRequest\x1a(.storagelambda.GetStatefulResultResponse\"\x00\x30\x01\x62\x06proto3')



_CALLACTIONREQUEST = DESCRIPTOR.message_types_by_name['CallActionRequest']
_CALLACTIONREQUEST_ACTIONARGUMENTSENTRY = _CALLACTIONREQUEST.nested_types_by_name['ActionArgumentsEntry']
_CALLSTATELESSACTIONRESPONSE = DESCRIPTOR.message_types_by_name['CallStatelessActionResponse']
_CALLSTATEFULACTIONREQUEST = DESCRIPTOR.message_types_by_name['CallStatefulActionRequest']
_CALLSTATEFULACTIONREQUEST_ACTIONARGUMENTSENTRY = _CALLSTATEFULACTIONREQUEST.nested_types_by_name['ActionArgumentsEntry']
_CALLSTATEFULACTIONRESPONSE = DESCRIPTOR.message_types_by_name['CallStatefulActionResponse']
_GETSTATEFULRESULTREQUEST = DESCRIPTOR.message_types_by_name['GetStatefulResultRequest']
_GETSTATEFULRESULTRESPONSE = DESCRIPTOR.message_types_by_name['GetStatefulResultResponse']
CallActionRequest = _reflection.GeneratedProtocolMessageType('CallActionRequest', (_message.Message,), {

  'ActionArgumentsEntry' : _reflection.GeneratedProtocolMessageType('ActionArgumentsEntry', (_message.Message,), {
    'DESCRIPTOR' : _CALLACTIONREQUEST_ACTIONARGUMENTSENTRY,
    '__module__' : 'service_pb2'
    # @@protoc_insertion_point(class_scope:storagelambda.CallActionRequest.ActionArgumentsEntry)
    })
  ,
  'DESCRIPTOR' : _CALLACTIONREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:storagelambda.CallActionRequest)
  })
_sym_db.RegisterMessage(CallActionRequest)
_sym_db.RegisterMessage(CallActionRequest.ActionArgumentsEntry)

CallStatelessActionResponse = _reflection.GeneratedProtocolMessageType('CallStatelessActionResponse', (_message.Message,), {
  'DESCRIPTOR' : _CALLSTATELESSACTIONRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:storagelambda.CallStatelessActionResponse)
  })
_sym_db.RegisterMessage(CallStatelessActionResponse)

CallStatefulActionRequest = _reflection.GeneratedProtocolMessageType('CallStatefulActionRequest', (_message.Message,), {

  'ActionArgumentsEntry' : _reflection.GeneratedProtocolMessageType('ActionArgumentsEntry', (_message.Message,), {
    'DESCRIPTOR' : _CALLSTATEFULACTIONREQUEST_ACTIONARGUMENTSENTRY,
    '__module__' : 'service_pb2'
    # @@protoc_insertion_point(class_scope:storagelambda.CallStatefulActionRequest.ActionArgumentsEntry)
    })
  ,
  'DESCRIPTOR' : _CALLSTATEFULACTIONREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:storagelambda.CallStatefulActionRequest)
  })
_sym_db.RegisterMessage(CallStatefulActionRequest)
_sym_db.RegisterMessage(CallStatefulActionRequest.ActionArgumentsEntry)

CallStatefulActionResponse = _reflection.GeneratedProtocolMessageType('CallStatefulActionResponse', (_message.Message,), {
  'DESCRIPTOR' : _CALLSTATEFULACTIONRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:storagelambda.CallStatefulActionResponse)
  })
_sym_db.RegisterMessage(CallStatefulActionResponse)

GetStatefulResultRequest = _reflection.GeneratedProtocolMessageType('GetStatefulResultRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSTATEFULRESULTREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:storagelambda.GetStatefulResultRequest)
  })
_sym_db.RegisterMessage(GetStatefulResultRequest)

GetStatefulResultResponse = _reflection.GeneratedProtocolMessageType('GetStatefulResultResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSTATEFULRESULTRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:storagelambda.GetStatefulResultResponse)
  })
_sym_db.RegisterMessage(GetStatefulResultResponse)

_STORAGELAMBDASERVICE = DESCRIPTOR.services_by_name['StorageLambdaService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CALLACTIONREQUEST_ACTIONARGUMENTSENTRY._options = None
  _CALLACTIONREQUEST_ACTIONARGUMENTSENTRY._serialized_options = b'8\001'
  _CALLSTATEFULACTIONREQUEST_ACTIONARGUMENTSENTRY._options = None
  _CALLSTATEFULACTIONREQUEST_ACTIONARGUMENTSENTRY._serialized_options = b'8\001'
  _CALLACTIONREQUEST._serialized_start=33
  _CALLACTIONREQUEST._serialized_end=210
  _CALLACTIONREQUEST_ACTIONARGUMENTSENTRY._serialized_start=156
  _CALLACTIONREQUEST_ACTIONARGUMENTSENTRY._serialized_end=210
  _CALLSTATELESSACTIONRESPONSE._serialized_start=212
  _CALLSTATELESSACTIONRESPONSE._serialized_end=271
  _CALLSTATEFULACTIONREQUEST._serialized_start=274
  _CALLSTATEFULACTIONREQUEST._serialized_end=467
  _CALLSTATEFULACTIONREQUEST_ACTIONARGUMENTSENTRY._serialized_start=156
  _CALLSTATEFULACTIONREQUEST_ACTIONARGUMENTSENTRY._serialized_end=210
  _CALLSTATEFULACTIONRESPONSE._serialized_start=469
  _CALLSTATEFULACTIONRESPONSE._serialized_end=529
  _GETSTATEFULRESULTREQUEST._serialized_start=531
  _GETSTATEFULRESULTREQUEST._serialized_end=588
  _GETSTATEFULRESULTRESPONSE._serialized_start=590
  _GETSTATEFULRESULTRESPONSE._serialized_end=647
  _STORAGELAMBDASERVICE._serialized_start=650
  _STORAGELAMBDASERVICE._serialized_end=992
# @@protoc_insertion_point(module_scope)
