apiVersion: v1
kind: ConfigMap
metadata:
  name: s3proxy-properties
  namespace: default
data:
  s3-properties: |
    s3proxy.endpoint=http://0.0.0.0:8080
    s3proxy.authorization=aws-v2-or-v4
    s3proxy.identity=${S3_ACCESS_KEY_ID}
    s3proxy.credential=${S3_SECRET_ACCESS_KEY}
    actives3proxy.manifest=/opt/s3proxy/activeS3manifest.yaml
    jclouds.provider=s3
    jclouds.identity=${S3_ACCESS_KEY_ID}
    jclouds.credential=${S3_SECRET_ACCESS_KEY}
    jclouds.endpoint=${S3_ENDPOINT}