# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: module_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14module_service.proto\x12\rstoragelambda\"\xfc\x01\n\x11\x43\x61llActionRequest\x12\x13\n\x0b\x61\x63tion_name\x18\x01 \x01(\t\x12\x45\n\x0b\x61\x63tion_args\x18\x02 \x03(\x0b\x32\x30.storagelambda.CallActionRequest.ActionArgsEntry\x12\x0e\n\x06\x62ucket\x18\x03 \x01(\t\x12\x0b\n\x03key\x18\x04 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x05 \x01(\t\x12%\n\x06method\x18\x06 \x01(\x0e\x32\x15.storagelambda.Method\x1a\x31\n\x0f\x41\x63tionArgsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\";\n\x1b\x43\x61llStatelessActionResponse\x12\r\n\x05\x66inal\x18\x01 \x01(\x08\x12\r\n\x05\x63hunk\x18\n \x01(\x0c\"\xb2\x01\n\x19\x43\x61llStatefulActionRequest\x12\x13\n\x0b\x61\x63tion_name\x18\x01 \x01(\t\x12M\n\x0b\x61\x63tion_args\x18\x02 \x03(\x0b\x32\x38.storagelambda.CallStatefulActionRequest.ActionArgsEntry\x1a\x31\n\x0f\x41\x63tionArgsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"<\n\x1a\x43\x61llStatefulActionResponse\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\r\n\x05parts\x18\x02 \x01(\x05\"9\n\x18GetStatefulResultRequest\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\x0c\n\x04part\x18\x02 \x01(\x05\"9\n\x19GetStatefulResultResponse\x12\r\n\x05\x66inal\x18\x01 \x01(\x08\x12\r\n\x05\x63hunk\x18\n \x01(\x0c*\x1a\n\x06Method\x12\x07\n\x03GET\x10\x00\x12\x07\n\x03PUT\x10\x01\x32\xd5\x02\n\x13StorageLambdaModule\x12g\n\x13\x43\x61llStatelessAction\x12 .storagelambda.CallActionRequest\x1a*.storagelambda.CallStatelessActionResponse\"\x00\x30\x01\x12\x63\n\x12\x43\x61llStatefulAction\x12 .storagelambda.CallActionRequest\x1a).storagelambda.CallStatefulActionResponse\"\x00\x12p\n\x17GetStatefulActionResult\x12\'.storagelambda.GetStatefulResultRequest\x1a(.storagelambda.GetStatefulResultResponse\"\x00\x30\x01\x62\x06proto3')

_METHOD = DESCRIPTOR.enum_types_by_name['Method']
Method = enum_type_wrapper.EnumTypeWrapper(_METHOD)
GET = 0
PUT = 1


_CALLACTIONREQUEST = DESCRIPTOR.message_types_by_name['CallActionRequest']
_CALLACTIONREQUEST_ACTIONARGSENTRY = _CALLACTIONREQUEST.nested_types_by_name['ActionArgsEntry']
_CALLSTATELESSACTIONRESPONSE = DESCRIPTOR.message_types_by_name['CallStatelessActionResponse']
_CALLSTATEFULACTIONREQUEST = DESCRIPTOR.message_types_by_name['CallStatefulActionRequest']
_CALLSTATEFULACTIONREQUEST_ACTIONARGSENTRY = _CALLSTATEFULACTIONREQUEST.nested_types_by_name['ActionArgsEntry']
_CALLSTATEFULACTIONRESPONSE = DESCRIPTOR.message_types_by_name['CallStatefulActionResponse']
_GETSTATEFULRESULTREQUEST = DESCRIPTOR.message_types_by_name['GetStatefulResultRequest']
_GETSTATEFULRESULTRESPONSE = DESCRIPTOR.message_types_by_name['GetStatefulResultResponse']
CallActionRequest = _reflection.GeneratedProtocolMessageType('CallActionRequest', (_message.Message,), {

  'ActionArgsEntry' : _reflection.GeneratedProtocolMessageType('ActionArgsEntry', (_message.Message,), {
    'DESCRIPTOR' : _CALLACTIONREQUEST_ACTIONARGSENTRY,
    '__module__' : 'module_service_pb2'
    # @@protoc_insertion_point(class_scope:storagelambda.CallActionRequest.ActionArgsEntry)
    })
  ,
  'DESCRIPTOR' : _CALLACTIONREQUEST,
  '__module__' : 'module_service_pb2'
  # @@protoc_insertion_point(class_scope:storagelambda.CallActionRequest)
  })
_sym_db.RegisterMessage(CallActionRequest)
_sym_db.RegisterMessage(CallActionRequest.ActionArgsEntry)

CallStatelessActionResponse = _reflection.GeneratedProtocolMessageType('CallStatelessActionResponse', (_message.Message,), {
  'DESCRIPTOR' : _CALLSTATELESSACTIONRESPONSE,
  '__module__' : 'module_service_pb2'
  # @@protoc_insertion_point(class_scope:storagelambda.CallStatelessActionResponse)
  })
_sym_db.RegisterMessage(CallStatelessActionResponse)

CallStatefulActionRequest = _reflection.GeneratedProtocolMessageType('CallStatefulActionRequest', (_message.Message,), {

  'ActionArgsEntry' : _reflection.GeneratedProtocolMessageType('ActionArgsEntry', (_message.Message,), {
    'DESCRIPTOR' : _CALLSTATEFULACTIONREQUEST_ACTIONARGSENTRY,
    '__module__' : 'module_service_pb2'
    # @@protoc_insertion_point(class_scope:storagelambda.CallStatefulActionRequest.ActionArgsEntry)
    })
  ,
  'DESCRIPTOR' : _CALLSTATEFULACTIONREQUEST,
  '__module__' : 'module_service_pb2'
  # @@protoc_insertion_point(class_scope:storagelambda.CallStatefulActionRequest)
  })
_sym_db.RegisterMessage(CallStatefulActionRequest)
_sym_db.RegisterMessage(CallStatefulActionRequest.ActionArgsEntry)

CallStatefulActionResponse = _reflection.GeneratedProtocolMessageType('CallStatefulActionResponse', (_message.Message,), {
  'DESCRIPTOR' : _CALLSTATEFULACTIONRESPONSE,
  '__module__' : 'module_service_pb2'
  # @@protoc_insertion_point(class_scope:storagelambda.CallStatefulActionResponse)
  })
_sym_db.RegisterMessage(CallStatefulActionResponse)

GetStatefulResultRequest = _reflection.GeneratedProtocolMessageType('GetStatefulResultRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSTATEFULRESULTREQUEST,
  '__module__' : 'module_service_pb2'
  # @@protoc_insertion_point(class_scope:storagelambda.GetStatefulResultRequest)
  })
_sym_db.RegisterMessage(GetStatefulResultRequest)

GetStatefulResultResponse = _reflection.GeneratedProtocolMessageType('GetStatefulResultResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSTATEFULRESULTRESPONSE,
  '__module__' : 'module_service_pb2'
  # @@protoc_insertion_point(class_scope:storagelambda.GetStatefulResultResponse)
  })
_sym_db.RegisterMessage(GetStatefulResultResponse)

_STORAGELAMBDAMODULE = DESCRIPTOR.services_by_name['StorageLambdaModule']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CALLACTIONREQUEST_ACTIONARGSENTRY._options = None
  _CALLACTIONREQUEST_ACTIONARGSENTRY._serialized_options = b'8\001'
  _CALLSTATEFULACTIONREQUEST_ACTIONARGSENTRY._options = None
  _CALLSTATEFULACTIONREQUEST_ACTIONARGSENTRY._serialized_options = b'8\001'
  _METHOD._serialized_start=716
  _METHOD._serialized_end=742
  _CALLACTIONREQUEST._serialized_start=40
  _CALLACTIONREQUEST._serialized_end=292
  _CALLACTIONREQUEST_ACTIONARGSENTRY._serialized_start=243
  _CALLACTIONREQUEST_ACTIONARGSENTRY._serialized_end=292
  _CALLSTATELESSACTIONRESPONSE._serialized_start=294
  _CALLSTATELESSACTIONRESPONSE._serialized_end=353
  _CALLSTATEFULACTIONREQUEST._serialized_start=356
  _CALLSTATEFULACTIONREQUEST._serialized_end=534
  _CALLSTATEFULACTIONREQUEST_ACTIONARGSENTRY._serialized_start=243
  _CALLSTATEFULACTIONREQUEST_ACTIONARGSENTRY._serialized_end=292
  _CALLSTATEFULACTIONRESPONSE._serialized_start=536
  _CALLSTATEFULACTIONRESPONSE._serialized_end=596
  _GETSTATEFULRESULTREQUEST._serialized_start=598
  _GETSTATEFULRESULTREQUEST._serialized_end=655
  _GETSTATEFULRESULTRESPONSE._serialized_start=657
  _GETSTATEFULRESULTRESPONSE._serialized_end=714
  _STORAGELAMBDAMODULE._serialized_start=745
  _STORAGELAMBDAMODULE._serialized_end=1086
# @@protoc_insertion_point(module_scope)
