# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import module_service_pb2 as module__service__pb2


class StorageLambdaModuleStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallStatelessAction = channel.unary_stream(
                '/storagelambda.StorageLambdaModule/CallStatelessAction',
                request_serializer=module__service__pb2.CallActionRequest.SerializeToString,
                response_deserializer=module__service__pb2.CallStatelessActionResponse.FromString,
                )
        self.CallStatefulAction = channel.unary_unary(
                '/storagelambda.StorageLambdaModule/CallStatefulAction',
                request_serializer=module__service__pb2.CallActionRequest.SerializeToString,
                response_deserializer=module__service__pb2.CallStatefulActionResponse.FromString,
                )
        self.GetStatefulActionResult = channel.unary_stream(
                '/storagelambda.StorageLambdaModule/GetStatefulActionResult',
                request_serializer=module__service__pb2.GetStatefulResultRequest.SerializeToString,
                response_deserializer=module__service__pb2.GetStatefulResultResponse.FromString,
                )


class StorageLambdaModuleServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CallStatelessAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallStatefulAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatefulActionResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageLambdaModuleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallStatelessAction': grpc.unary_stream_rpc_method_handler(
                    servicer.CallStatelessAction,
                    request_deserializer=module__service__pb2.CallActionRequest.FromString,
                    response_serializer=module__service__pb2.CallStatelessActionResponse.SerializeToString,
            ),
            'CallStatefulAction': grpc.unary_unary_rpc_method_handler(
                    servicer.CallStatefulAction,
                    request_deserializer=module__service__pb2.CallActionRequest.FromString,
                    response_serializer=module__service__pb2.CallStatefulActionResponse.SerializeToString,
            ),
            'GetStatefulActionResult': grpc.unary_stream_rpc_method_handler(
                    servicer.GetStatefulActionResult,
                    request_deserializer=module__service__pb2.GetStatefulResultRequest.FromString,
                    response_serializer=module__service__pb2.GetStatefulResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'storagelambda.StorageLambdaModule', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StorageLambdaModule(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CallStatelessAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/storagelambda.StorageLambdaModule/CallStatelessAction',
            module__service__pb2.CallActionRequest.SerializeToString,
            module__service__pb2.CallStatelessActionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CallStatefulAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/storagelambda.StorageLambdaModule/CallStatefulAction',
            module__service__pb2.CallActionRequest.SerializeToString,
            module__service__pb2.CallStatefulActionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatefulActionResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/storagelambda.StorageLambdaModule/GetStatefulActionResult',
            module__service__pb2.GetStatefulResultRequest.SerializeToString,
            module__service__pb2.GetStatefulResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
